In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
sys.path.append("./../../")
from src.utils import *
import itertools
import ast


from itertools import chain, combinations

In [62]:
# Load dataset
ds = load_jsonl_file('./../../../data/MATE-dev/mm_0shot_llava_hfllava_1.5_7b_hf.jsonl')
mate_df = pd.read_csv('./../../data/mate_df.csv', index_col=0)

5500it [00:01, 5286.02it/s]

In [61]:
create_mate_df = False
if create_mate_df:
    mate_df = pd.DataFrame(
        {'idx': list(range(0,len(ds))),
        'image': [data['image'] for data in ds],
        'object_count': [data['object_count'] for data in ds],
        'color': [[obj['color'] for obj in data['scene']['objects']] for data in ds],
        'shape': [[obj['shape'] for obj in data['scene']['objects']] for data in ds],
        'material': [[obj['material'] for obj in data['scene']['objects']] for data in ds],
        'color_shape': [[f"{obj['color']}_{obj['shape']}" for obj in data['scene']['objects']] for data in ds],
        'color_material': [[f"{obj['color']}_{obj['material']}" for obj in data['scene']['objects']] for data in ds],
        'shape_material': [[f"{obj['shape']}_{obj['material']}" for obj in data['scene']['objects']] for data in ds],
        'color_shape_material': [[f"{obj['color']}_{obj['shape']}_{obj['material']}" for obj in data['scene']['objects']] for data in ds],
        'size': [[obj['size'] for obj in data['scene']['objects']] for data in ds]}
    )

    mate_df['all'] = mate_df.apply(
        lambda row: row["color"] + row["shape"] + row["material"] +\
                    row["color_shape"] + row["shape_material"] + row["color_material"] + row["color_shape_material"],
        axis=1
    )

    mate_df.to_csv('./../../data/mate_df.csv')

In [69]:
# sizes of object
object_size_ls = set([item for items in mate_df['size'].to_list() for item in ast.literal_eval(items)])
print(f"sizes: {object_size_ls}")

# color of object
color_ls = set([item for items in mate_df['color'].to_list() for item in ast.literal_eval(items)])
print(f"colors: {color_ls}")

# shapes of object
shape_ls = set([item for items in mate_df['shape'].to_list() for item in ast.literal_eval(items)])
print(f"shape: {shape_ls}")

# material of object
material_ls = set([item for items in mate_df['material'].to_list() for item in ast.literal_eval(items)])
print(f"material: {material_ls}")

task_dict = {
    'size': [0.351, 0.701, 0.35, 0.7],
    'color': ['gray', 'yellow', 'red', 'blue', 'brown', 'cyan', 'green', 'purple'],
    'shape': ['sphere', 'cone', 'cube', 'cylinder'],
    'material': ['rubber', 'metal']
}

sizes: {0.351, 0.701, 0.35, 0.7}
colors: {'gray', 'yellow', 'red', 'blue', 'brown', 'cyan', 'green', 'purple'}
shape: {'sphere', 'cone', 'cube', 'cylinder'}
material: {'rubber', 'metal'}

In [10]:
# Number of objects
nobjects = list(range(0,12))

for i in nobjects:
    # Filter dataset for a specific number of objects 
    ds_ = [1 for data in ds if data['object_count'] == i]
    print(f"The number of examples with {i} objects is {len(ds_)}")

The number of examples with 0 objects is 0
The number of examples with 1 objects is 0
The number of examples with 2 objects is 0
The number of examples with 3 objects is 670
The number of examples with 4 objects is 696
The number of examples with 5 objects is 681
The number of examples with 6 objects is 674
The number of examples with 7 objects is 688
The number of examples with 8 objects is 746
The number of examples with 9 objects is 681
The number of examples with 10 objects is 664
The number of examples with 11 objects is 0

In [74]:
# Create list of combinations using color, shape and material with 100+ samples
combinations = []
combinations = combinations + list(itertools.product(task_dict['color']))
combinations = combinations + list(itertools.product(task_dict['shape']))
combinations = combinations + list(itertools.product(task_dict['material']))
combinations = combinations + list(itertools.product(task_dict['color'], task_dict['shape']))
combinations = combinations + list(itertools.product(task_dict['shape'], task_dict['material']))
combinations = combinations + list(itertools.product(task_dict['color'], task_dict['material']))
combinations = combinations + list(itertools.product(task_dict['color'], task_dict['shape'], task_dict['material']))

linear_probe_list_combination = []
linear_probe_list_nobj = []

for nobj in [3,5,7,9]:
    for combination in combinations:
        nsamples = len(mate_df[(mate_df['object_count'] == nobj) & (mate_df['all'].apply(lambda x: '_'.join(combination) in x))])
        if nsamples>99:
            print(f"The number of samples with {combination} objects: {nsamples}, nobjs: {nobj}")
            linear_probe_list_combination = linear_probe_list_combination + ['_'.join(combination)]
            linear_probe_list_nobj = linear_probe_list_nobj + [nobj]

The number of samples with ('gray',) objects: 225, nobjs: 3
The number of samples with ('yellow',) objects: 265, nobjs: 3
The number of samples with ('red',) objects: 257, nobjs: 3
The number of samples with ('blue',) objects: 246, nobjs: 3
The number of samples with ('brown',) objects: 278, nobjs: 3
The number of samples with ('cyan',) objects: 260, nobjs: 3
The number of samples with ('green',) objects: 253, nobjs: 3
The number of samples with ('purple',) objects: 226, nobjs: 3
The number of samples with ('sphere',) objects: 479, nobjs: 3
The number of samples with ('cone',) objects: 276, nobjs: 3
The number of samples with ('cube',) objects: 497, nobjs: 3
The number of samples with ('cylinder',) objects: 505, nobjs: 3
The number of samples with ('rubber',) objects: 585, nobjs: 3
The number of samples with ('metal',) objects: 594, nobjs: 3
The number of samples with ('brown', 'cylinder') objects: 101, nobjs: 3
The number of samples with ('sphere', 'rubber') objects: 262, nobjs: 3
The number of samples with ('sphere', 'metal') objects: 259, nobjs: 3
The number of samples with ('cone', 'rubber') objects: 127, nobjs: 3
The number of samples with ('cone', 'metal') objects: 150, nobjs: 3
The number of samples with ('cube', 'rubber') objects: 282, nobjs: 3
The number of samples with ('cube', 'metal') objects: 255, nobjs: 3
The number of samples with ('cylinder', 'rubber') objects: 243, nobjs: 3
The number of samples with ('cylinder', 'metal') objects: 304, nobjs: 3
The number of samples with ('gray', 'rubber') objects: 111, nobjs: 3
The number of samples with ('gray', 'metal') objects: 114, nobjs: 3
The number of samples with ('yellow', 'rubber') objects: 128, nobjs: 3
The number of samples with ('yellow', 'metal') objects: 137, nobjs: 3
The number of samples with ('red', 'rubber') objects: 118, nobjs: 3
The number of samples with ('red', 'metal') objects: 139, nobjs: 3
The number of samples with ('blue', 'rubber') objects: 123, nobjs: 3
The number of samples with ('blue', 'metal') objects: 123, nobjs: 3
The number of samples with ('brown', 'rubber') objects: 135, nobjs: 3
The number of samples with ('brown', 'metal') objects: 143, nobjs: 3
The number of samples with ('cyan', 'rubber') objects: 142, nobjs: 3
The number of samples with ('cyan', 'metal') objects: 118, nobjs: 3
The number of samples with ('green', 'rubber') objects: 113, nobjs: 3
The number of samples with ('green', 'metal') objects: 140, nobjs: 3
The number of samples with ('purple', 'metal') objects: 127, nobjs: 3
The number of samples with ('gray',) objects: 406, nobjs: 5
The number of samples with ('yellow',) objects: 424, nobjs: 5
The number of samples with ('red',) objects: 415, nobjs: 5
The number of samples with ('blue',) objects: 412, nobjs: 5
The number of samples with ('brown',) objects: 402, nobjs: 5
The number of samples with ('cyan',) objects: 411, nobjs: 5
The number of samples with ('green',) objects: 409, nobjs: 5
The number of samples with ('purple',) objects: 394, nobjs: 5
The number of samples with ('sphere',) objects: 614, nobjs: 5
The number of samples with ('cone',) objects: 351, nobjs: 5
The number of samples with ('cube',) objects: 610, nobjs: 5
The number of samples with ('cylinder',) objects: 614, nobjs: 5
The number of samples with ('rubber',) objects: 664, nobjs: 5
The number of samples with ('metal',) objects: 649, nobjs: 5
The number of samples with ('gray', 'sphere') objects: 124, nobjs: 5
The number of samples with ('gray', 'cube') objects: 128, nobjs: 5
The number of samples with ('gray', 'cylinder') objects: 128, nobjs: 5
The number of samples with ('yellow', 'sphere') objects: 118, nobjs: 5
The number of samples with ('yellow', 'cube') objects: 147, nobjs: 5
The number of samples with ('yellow', 'cylinder') objects: 123, nobjs: 5
The number of samples with ('red', 'sphere') objects: 130, nobjs: 5
The number of samples with ('red', 'cube') objects: 141, nobjs: 5
The number of samples with ('red', 'cylinder') objects: 125, nobjs: 5
The number of samples with ('blue', 'sphere') objects: 133, nobjs: 5
The number of samples with ('blue', 'cube') objects: 124, nobjs: 5
The number of samples with ('blue', 'cylinder') objects: 123, nobjs: 5
The number of samples with ('brown', 'sphere') objects: 121, nobjs: 5
The number of samples with ('brown', 'cube') objects: 113, nobjs: 5
The number of samples with ('brown', 'cylinder') objects: 135, nobjs: 5
The number of samples with ('cyan', 'sphere') objects: 137, nobjs: 5
The number of samples with ('cyan', 'cube') objects: 119, nobjs: 5
The number of samples with ('cyan', 'cylinder') objects: 117, nobjs: 5
The number of samples with ('green', 'sphere') objects: 135, nobjs: 5
The number of samples with ('green', 'cube') objects: 122, nobjs: 5
The number of samples with ('green', 'cylinder') objects: 119, nobjs: 5
The number of samples with ('purple', 'sphere') objects: 113, nobjs: 5
The number of samples with ('purple', 'cube') objects: 127, nobjs: 5
The number of samples with ('purple', 'cylinder') objects: 118, nobjs: 5
The number of samples with ('sphere', 'rubber') objects: 408, nobjs: 5
The number of samples with ('sphere', 'metal') objects: 377, nobjs: 5
The number of samples with ('cone', 'rubber') objects: 186, nobjs: 5
The number of samples with ('cone', 'metal') objects: 177, nobjs: 5
The number of samples with ('cube', 'rubber') objects: 410, nobjs: 5
The number of samples with ('cube', 'metal') objects: 373, nobjs: 5
The number of samples with ('cylinder', 'rubber') objects: 382, nobjs: 5
The number of samples with ('cylinder', 'metal') objects: 398, nobjs: 5
The number of samples with ('gray', 'rubber') objects: 206, nobjs: 5
The number of samples with ('gray', 'metal') objects: 207, nobjs: 5
The number of samples with ('yellow', 'rubber') objects: 231, nobjs: 5
The number of samples with ('yellow', 'metal') objects: 200, nobjs: 5
The number of samples with ('red', 'rubber') objects: 220, nobjs: 5
The number of samples with ('red', 'metal') objects: 208, nobjs: 5
The number of samples with ('blue', 'rubber') objects: 223, nobjs: 5
The number of samples with ('blue', 'metal') objects: 204, nobjs: 5
The number of samples with ('brown', 'rubber') objects: 198, nobjs: 5
The number of samples with ('brown', 'metal') objects: 211, nobjs: 5
The number of samples with ('cyan', 'rubber') objects: 204, nobjs: 5
The number of samples with ('cyan', 'metal') objects: 215, nobjs: 5
The number of samples with ('green', 'rubber') objects: 212, nobjs: 5
The number of samples with ('green', 'metal') objects: 203, nobjs: 5
The number of samples with ('purple', 'rubber') objects: 205, nobjs: 5
The number of samples with ('purple', 'metal') objects: 196, nobjs: 5
The number of samples with ('gray',) objects: 521, nobjs: 7
The number of samples with ('yellow',) objects: 493, nobjs: 7
The number of samples with ('red',) objects: 494, nobjs: 7
The number of samples with ('blue',) objects: 515, nobjs: 7
The number of samples with ('brown',) objects: 520, nobjs: 7
The number of samples with ('cyan',) objects: 522, nobjs: 7
The number of samples with ('green',) objects: 500, nobjs: 7
The number of samples with ('purple',) objects: 531, nobjs: 7
The number of samples with ('sphere',) objects: 667, nobjs: 7
The number of samples with ('cone',) objects: 438, nobjs: 7
The number of samples with ('cube',) objects: 663, nobjs: 7
The number of samples with ('cylinder',) objects: 666, nobjs: 7
The number of samples with ('rubber',) objects: 680, nobjs: 7
The number of samples with ('metal',) objects: 683, nobjs: 7
The number of samples with ('gray', 'sphere') objects: 185, nobjs: 7
The number of samples with ('gray', 'cube') objects: 167, nobjs: 7
The number of samples with ('gray', 'cylinder') objects: 189, nobjs: 7
The number of samples with ('yellow', 'sphere') objects: 169, nobjs: 7
The number of samples with ('yellow', 'cube') objects: 171, nobjs: 7
The number of samples with ('yellow', 'cylinder') objects: 161, nobjs: 7
The number of samples with ('red', 'sphere') objects: 174, nobjs: 7
The number of samples with ('red', 'cube') objects: 163, nobjs: 7
The number of samples with ('red', 'cylinder') objects: 154, nobjs: 7
The number of samples with ('blue', 'sphere') objects: 168, nobjs: 7
The number of samples with ('blue', 'cube') objects: 178, nobjs: 7
The number of samples with ('blue', 'cylinder') objects: 178, nobjs: 7
The number of samples with ('brown', 'sphere') objects: 167, nobjs: 7
The number of samples with ('brown', 'cube') objects: 180, nobjs: 7
The number of samples with ('brown', 'cylinder') objects: 170, nobjs: 7
The number of samples with ('cyan', 'sphere') objects: 174, nobjs: 7
The number of samples with ('cyan', 'cube') objects: 174, nobjs: 7
The number of samples with ('cyan', 'cylinder') objects: 178, nobjs: 7
The number of samples with ('green', 'sphere') objects: 177, nobjs: 7
The number of samples with ('green', 'cube') objects: 150, nobjs: 7
The number of samples with ('green', 'cylinder') objects: 168, nobjs: 7
The number of samples with ('purple', 'sphere') objects: 180, nobjs: 7
The number of samples with ('purple', 'cube') objects: 174, nobjs: 7
The number of samples with ('purple', 'cylinder') objects: 180, nobjs: 7
The number of samples with ('sphere', 'rubber') objects: 468, nobjs: 7
The number of samples with ('sphere', 'metal') objects: 471, nobjs: 7
The number of samples with ('cone', 'rubber') objects: 255, nobjs: 7
The number of samples with ('cone', 'metal') objects: 233, nobjs: 7
The number of samples with ('cube', 'rubber') objects: 457, nobjs: 7
The number of samples with ('cube', 'metal') objects: 466, nobjs: 7
The number of samples with ('cylinder', 'rubber') objects: 473, nobjs: 7
The number of samples with ('cylinder', 'metal') objects: 465, nobjs: 7
The number of samples with ('gray', 'rubber') objects: 295, nobjs: 7
The number of samples with ('gray', 'metal') objects: 269, nobjs: 7
The number of samples with ('yellow', 'rubber') objects: 271, nobjs: 7
The number of samples with ('yellow', 'metal') objects: 268, nobjs: 7
The number of samples with ('red', 'rubber') objects: 258, nobjs: 7
The number of samples with ('red', 'metal') objects: 272, nobjs: 7
The number of samples with ('blue', 'rubber') objects: 273, nobjs: 7
The number of samples with ('blue', 'metal') objects: 287, nobjs: 7
The number of samples with ('brown', 'rubber') objects: 302, nobjs: 7
The number of samples with ('brown', 'metal') objects: 254, nobjs: 7
The number of samples with ('cyan', 'rubber') objects: 273, nobjs: 7
The number of samples with ('cyan', 'metal') objects: 287, nobjs: 7
The number of samples with ('green', 'rubber') objects: 270, nobjs: 7
The number of samples with ('green', 'metal') objects: 264, nobjs: 7
The number of samples with ('purple', 'rubber') objects: 286, nobjs: 7
The number of samples with ('purple', 'metal') objects: 288, nobjs: 7
The number of samples with ('gray', 'cylinder', 'metal') objects: 101, nobjs: 7
The number of samples with ('brown', 'cylinder', 'rubber') objects: 107, nobjs: 7
The number of samples with ('cyan', 'sphere', 'rubber') objects: 101, nobjs: 7
The number of samples with ('gray',) objects: 568, nobjs: 9
The number of samples with ('yellow',) objects: 582, nobjs: 9
The number of samples with ('red',) objects: 560, nobjs: 9
The number of samples with ('blue',) objects: 578, nobjs: 9
The number of samples with ('brown',) objects: 562, nobjs: 9
The number of samples with ('cyan',) objects: 575, nobjs: 9
The number of samples with ('green',) objects: 564, nobjs: 9
The number of samples with ('purple',) objects: 569, nobjs: 9
The number of samples with ('sphere',) objects: 675, nobjs: 9
The number of samples with ('cone',) objects: 497, nobjs: 9
The number of samples with ('cube',) objects: 676, nobjs: 9
The number of samples with ('cylinder',) objects: 673, nobjs: 9
The number of samples with ('rubber',) objects: 681, nobjs: 9
The number of samples with ('metal',) objects: 679, nobjs: 9
The number of samples with ('gray', 'sphere') objects: 185, nobjs: 9
The number of samples with ('gray', 'cube') objects: 205, nobjs: 9
The number of samples with ('gray', 'cylinder') objects: 214, nobjs: 9
The number of samples with ('yellow', 'sphere') objects: 236, nobjs: 9
The number of samples with ('yellow', 'cube') objects: 198, nobjs: 9
The number of samples with ('yellow', 'cylinder') objects: 218, nobjs: 9
The number of samples with ('red', 'sphere') objects: 204, nobjs: 9
The number of samples with ('red', 'cube') objects: 187, nobjs: 9
The number of samples with ('red', 'cylinder') objects: 208, nobjs: 9
The number of samples with ('blue', 'sphere') objects: 225, nobjs: 9
The number of samples with ('blue', 'cube') objects: 204, nobjs: 9
The number of samples with ('blue', 'cylinder') objects: 195, nobjs: 9
The number of samples with ('brown', 'sphere') objects: 213, nobjs: 9
The number of samples with ('brown', 'cube') objects: 193, nobjs: 9
The number of samples with ('brown', 'cylinder') objects: 204, nobjs: 9
The number of samples with ('cyan', 'sphere') objects: 200, nobjs: 9
The number of samples with ('cyan', 'cube') objects: 208, nobjs: 9
The number of samples with ('cyan', 'cylinder') objects: 211, nobjs: 9
The number of samples with ('green', 'sphere') objects: 213, nobjs: 9
The number of samples with ('green', 'cube') objects: 219, nobjs: 9
The number of samples with ('green', 'cylinder') objects: 206, nobjs: 9
The number of samples with ('purple', 'sphere') objects: 213, nobjs: 9
The number of samples with ('purple', 'cube') objects: 208, nobjs: 9
The number of samples with ('purple', 'cylinder') objects: 206, nobjs: 9
The number of samples with ('sphere', 'rubber') objects: 531, nobjs: 9
The number of samples with ('sphere', 'metal') objects: 505, nobjs: 9
The number of samples with ('cone', 'rubber') objects: 280, nobjs: 9
The number of samples with ('cone', 'metal') objects: 280, nobjs: 9
The number of samples with ('cube', 'rubber') objects: 515, nobjs: 9
The number of samples with ('cube', 'metal') objects: 498, nobjs: 9
The number of samples with ('cylinder', 'rubber') objects: 523, nobjs: 9
The number of samples with ('cylinder', 'metal') objects: 490, nobjs: 9
The number of samples with ('gray', 'rubber') objects: 327, nobjs: 9
The number of samples with ('gray', 'metal') objects: 305, nobjs: 9
The number of samples with ('yellow', 'rubber') objects: 353, nobjs: 9
The number of samples with ('yellow', 'metal') objects: 321, nobjs: 9
The number of samples with ('red', 'rubber') objects: 330, nobjs: 9
The number of samples with ('red', 'metal') objects: 312, nobjs: 9
The number of samples with ('blue', 'rubber') objects: 341, nobjs: 9
The number of samples with ('blue', 'metal') objects: 314, nobjs: 9
The number of samples with ('brown', 'rubber') objects: 312, nobjs: 9
The number of samples with ('brown', 'metal') objects: 327, nobjs: 9
The number of samples with ('cyan', 'rubber') objects: 354, nobjs: 9
The number of samples with ('cyan', 'metal') objects: 315, nobjs: 9
The number of samples with ('green', 'rubber') objects: 330, nobjs: 9
The number of samples with ('green', 'metal') objects: 314, nobjs: 9
The number of samples with ('purple', 'rubber') objects: 328, nobjs: 9
The number of samples with ('purple', 'metal') objects: 344, nobjs: 9
The number of samples with ('gray', 'cube', 'rubber') objects: 109, nobjs: 9
The number of samples with ('gray', 'cube', 'metal') objects: 102, nobjs: 9
The number of samples with ('gray', 'cylinder', 'rubber') objects: 122, nobjs: 9
The number of samples with ('gray', 'cylinder', 'metal') objects: 100, nobjs: 9
The number of samples with ('yellow', 'sphere', 'rubber') objects: 132, nobjs: 9
The number of samples with ('yellow', 'sphere', 'metal') objects: 115, nobjs: 9
The number of samples with ('yellow', 'cube', 'rubber') objects: 118, nobjs: 9
The number of samples with ('yellow', 'cylinder', 'rubber') objects: 111, nobjs: 9
The number of samples with ('yellow', 'cylinder', 'metal') objects: 113, nobjs: 9
The number of samples with ('red', 'sphere', 'rubber') objects: 108, nobjs: 9
The number of samples with ('red', 'sphere', 'metal') objects: 105, nobjs: 9
The number of samples with ('red', 'cube', 'rubber') objects: 100, nobjs: 9
The number of samples with ('red', 'cylinder', 'rubber') objects: 118, nobjs: 9
The number of samples with ('red', 'cylinder', 'metal') objects: 100, nobjs: 9
The number of samples with ('blue', 'sphere', 'rubber') objects: 115, nobjs: 9
The number of samples with ('blue', 'sphere', 'metal') objects: 123, nobjs: 9
The number of samples with ('blue', 'cube', 'rubber') objects: 116, nobjs: 9
The number of samples with ('blue', 'cylinder', 'rubber') objects: 107, nobjs: 9
The number of samples with ('blue', 'cylinder', 'metal') objects: 104, nobjs: 9
The number of samples with ('brown', 'sphere', 'metal') objects: 123, nobjs: 9
The number of samples with ('brown', 'cube', 'rubber') objects: 102, nobjs: 9
The number of samples with ('brown', 'cylinder', 'rubber') objects: 103, nobjs: 9
The number of samples with ('brown', 'cylinder', 'metal') objects: 105, nobjs: 9
The number of samples with ('cyan', 'sphere', 'rubber') objects: 118, nobjs: 9
The number of samples with ('cyan', 'cube', 'rubber') objects: 109, nobjs: 9
The number of samples with ('cyan', 'cube', 'metal') objects: 108, nobjs: 9
The number of samples with ('cyan', 'cylinder', 'rubber') objects: 123, nobjs: 9
The number of samples with ('green', 'sphere', 'rubber') objects: 116, nobjs: 9
The number of samples with ('green', 'sphere', 'metal') objects: 107, nobjs: 9
The number of samples with ('green', 'cube', 'rubber') objects: 104, nobjs: 9
The number of samples with ('green', 'cube', 'metal') objects: 125, nobjs: 9
The number of samples with ('green', 'cylinder', 'rubber') objects: 113, nobjs: 9
The number of samples with ('green', 'cylinder', 'metal') objects: 101, nobjs: 9
The number of samples with ('purple', 'sphere', 'rubber') objects: 110, nobjs: 9
The number of samples with ('purple', 'sphere', 'metal') objects: 119, nobjs: 9
The number of samples with ('purple', 'cube', 'metal') objects: 120, nobjs: 9
The number of samples with ('purple', 'cylinder', 'rubber') objects: 118, nobjs: 9
The number of samples with ('purple', 'cylinder', 'metal') objects: 101, nobjs: 9

In [75]:
linear_probe_df = pd.DataFrame({
    'combinations': linear_probe_list_combination,
    'nobj': linear_probe_list_nobj
})

linear_probe_df

               combinations  nobj
0                      gray     3
1                    yellow     3
2                       red     3
3                      blue     3
4                     brown     3
..                      ...   ...
260    purple_sphere_rubber     9
261     purple_sphere_metal     9
262       purple_cube_metal     9
263  purple_cylinder_rubber     9
264   purple_cylinder_metal     9

[265 rows x 2 columns]

In [18]:
mate_df[(mate_df['object_count']==3) & (mate_df['color_shape'].apply(lambda x: 'gray_cylinder' in x))]

,idx,image,object_count,color,shape,material,color_shape,color_material,shape_material,color_shape_material,size
17,17,3e99992732c50e1307349865b563778d.png,3,"['blue', 'gray', 'yellow']","['cone', 'cylinder', 'cube']","['metal', 'rubber', 'rubber']","['blue_cone', 'gray_cylinder', 'yellow_cube']","['blue_metal', 'gray_rubber', 'yellow_rubber']","['cone_metal', 'cylinder_rubber', 'cube_rubber']","['blue_cone_metal', 'gray_cylinder_rubber', 'y...","[0.351, 0.7, 0.351]"
189,189,bb8dfe0d9814d0e0dcb22fd6c8fc1ad3.png,3,"['gray', 'red', 'yellow']","['cylinder', 'sphere', 'cylinder']","['rubber', 'metal', 'rubber']","['gray_cylinder', 'red_sphere', 'yellow_cylind...","['gray_rubber', 'red_metal', 'yellow_rubber']","['cylinder_rubber', 'sphere_metal', 'cylinder_...","['gray_cylinder_rubber', 'red_sphere_metal', '...","[0.351, 0.351, 0.701]"
211,211,ab8b667a364d57b77cf04656f7e318cc.png,3,"['gray', 'cyan', 'red']","['cylinder', 'cube', 'cone']","['rubber', 'rubber', 'rubber']","['gray_cylinder', 'cyan_cube', 'red_cone']","['gray_rubber', 'cyan_rubber', 'red_rubber']","['cylinder_rubber', 'cube_rubber', 'cone_rubber']","['gray_cylinder_rubber', 'cyan_cube_rubber', '...","[0.351, 0.7, 0.351]"
236,236,867f856462d189cf035207d17ff81d87.png,3,"['blue', 'gray', 'red']","['cylinder', 'cylinder', 'sphere']","['metal', 'metal', 'rubber']","['blue_cylinder', 'gray_cylinder', 'red_sphere']","['blue_metal', 'gray_metal', 'red_rubber']","['cylinder_metal', 'cylinder_metal', 'sphere_r...","['blue_cylinder_metal', 'gray_cylinder_metal',...","[0.701, 0.7, 0.701]"
249,249,abcfb61efc820a8eb42833494a224fde.png,3,"['brown', 'gray', 'purple']","['cube', 'cylinder', 'sphere']","['rubber', 'metal', 'metal']","['brown_cube', 'gray_cylinder', 'purple_sphere']","['brown_rubber', 'gray_metal', 'purple_metal']","['cube_rubber', 'cylinder_metal', 'sphere_metal']","['brown_cube_rubber', 'gray_cylinder_metal', '...","[0.701, 0.701, 0.351]"
...,...,...,...,...,...,...,...,...,...,...,...
5144,5144,21983e4f3b760e07033f13c02724b6d9.png,3,"['blue', 'green', 'gray']","['cube', 'sphere', 'cylinder']","['rubber', 'rubber', 'metal']","['blue_cube', 'green_sphere', 'gray_cylinder']","['blue_rubber', 'green_rubber', 'gray_metal']","['cube_rubber', 'sphere_rubber', 'cylinder_met...","['blue_cube_rubber', 'green_sphere_rubber', 'g...","[0.7, 0.7, 0.351]"
5177,5177,3de1313a059e259ed464c60a5b5b7aa9.png,3,"['red', 'gray', 'green']","['sphere', 'cylinder', 'cube']","['rubber', 'rubber', 'metal']","['red_sphere', 'gray_cylinder', 'green_cube']","['red_rubber', 'gray_rubber', 'green_metal']","['sphere_rubber', 'cylinder_rubber', 'cube_met...","['red_sphere_rubber', 'gray_cylinder_rubber', ...","[0.351, 0.35, 0.351]"
5189,5189,4261cd605b0cf133d040bf438bcb0ed8.png,3,"['yellow', 'gray', 'cyan']","['sphere', 'cylinder', 'cylinder']","['metal', 'rubber', 'metal']","['yellow_sphere', 'gray_cylinder', 'cyan_cylin...","['yellow_metal', 'gray_rubber', 'cyan_metal']","['sphere_metal', 'cylinder_rubber', 'cylinder_...","['yellow_sphere_metal', 'gray_cylinder_rubber'...","[0.7, 0.351, 0.701]"
5295,5295,87bfa5be7db3796562c2f95f762ebd76.png,3,"['gray', 'cyan', 'yellow']","['cylinder', 'cube', 'cone']","['metal', 'metal', 'metal']","['gray_cylinder', 'cyan_cube', 'yellow_cone']","['gray_metal', 'cyan_metal', 'yellow_metal']","['cylinder_metal', 'cube_metal', 'cone_metal']","['gray_cylinder_metal', 'cyan_cube_metal', 'ye...","[0.7, 0.701, 0.7]"
5441,5441,118721e68f04556b082846b25840220e.png,3,"['purple', 'gray', 'blue']","['cube', 'cylinder', 'sphere']","['metal', 'rubber', 'metal']","['purple_cube', 'gray_cylinder', 'blue_sphere']","['purple_metal', 'gray_rubber', 'blue_metal']","['cube_metal', 'cylinder_rubber', 'sphere_metal']","['purple_cube_metal', 'gray_cylinder_rubber', ...","[0.7, 0.351, 0.7]"